### ISSUE TITLE
"Failed to Execute" error when using Project Z tool

### ISSUE THREAD

**Issue by Chapman503** [Esri/collector-tools#10] opened 2017-05-23 19:57 UTC
Greetings,

I am trying to use the Project Z tool to convert point data collected using an Arrow 200 GNSS (data collected is in WGS84(G1674)/ITRF08 w Z values in meters) to NAD 1983 HARN StatePlane Oregon North FIPS 3601 Feet Intl.  I am using ArcGIS 10.4.1.  The conversion seems to work fine up to the point of actually saving the Feature Class in the location specified- see below
![image](https://cloud.githubusercontent.com/assets/28906708/26373621/129c3762-3fb7-11e7-9ca4-aa36a34ebe12.png)

These are the setting I am using for conversion in the Project Z tool-
![image](https://cloud.githubusercontent.com/assets/28906708/26373746/97549e54-3fb7-11e7-95f7-9d391b38310e.png)

I have set the environment option to point to where I want to save the output, tried various drives Local & Network.  Any suggestions would be greatly appreciated!
MC

**Comment by apulverizer** [comment] 2017-05-26 14:52
Hi @Chapman503 

A couple of things you could try which might narrow down the problem.

1. Can you try to output to a Feature Class in a Geodatabase? It seems to be writing to a shapefile?

2. Can you run the Project GP tool on this same source feature class with the same output location?

If you still have issues, could you post the full log messages here as text, not screenshot?

**Comment by Kevin-GIS** [comment] 2019-11-16 01:04
Closing this issue for the time being, can reopen if this issue is still reproducible.

**Closed by Kevin-GIS** 2019-11-16 01:04 UTC
