### ISSUE TITLE
Add GNSS Metadata fields (Pro) error messages "Tool has failed to open..."

### ISSUE THREAD

**Issue by Lmawhinney7175** [Esri/collector-tools#61] opened 2018-07-20 02:13 UTC
I am working in 2.0.1 ArcPro.  I downloaded and extracted the collector-tools.  When I double click to open the "Add GNSS Metadata Fields (Pro) - FeatureClass" tool, I get the following error message.  

Tool has failed to open: S:\GIS_Data\Mapping\7429Production\MAPS\Production\Laura\Mobile Field\GPS Pilot Program\JOC Contract\collector-tools-master(4)\collector-tools-master\CollectorUtils\pro\CollectorUtils_Pro.tbx\AddGNSSFieldsPro

If you have any idea of what the issue is, please let me know.

Thank you,

Laura

**Comment by niti5425** [comment] 2018-07-20 23:07
@Lmawhinney7175 Have you added the toolbox  (CollectorUtils_Pro.tbx) to ArcGIS Pro?

**Comment by Lmawhinney7175** [comment] 2018-07-20 23:08
Hello,

Yes.  I add the toolbox to ArcGIS Pro?

**Comment by niti5425** [comment] 2018-07-20 23:14
@Lmawhinney7175  I'm not able to reproduce the error. 

![image](https://user-images.githubusercontent.com/26557666/43028935-c0ee0f7a-8c37-11e8-9437-e76bb171c6ee.png)

![image](https://user-images.githubusercontent.com/26557666/43028954-e0aae78e-8c37-11e8-8bc5-b6017b492b4f.png)

**Comment by Lmawhinney7175** [comment] 2018-07-20 23:20
Thank you for responding and helping.  It makes it challenging to trouble shoot if someone can't reproduce the error.  There isn't much to go on.

![gnss_toolbox](https://user-images.githubusercontent.com/23640622/43029117-c0f4e524-8c38-11e8-948d-845d9fe143b0.jpg)
![gnss_error_message](https://user-images.githubusercontent.com/23640622/43029119-c16d19ea-8c38-11e8-80e1-2fa54ff790dd.jpg)

Laura

**Comment by niti5425** [comment] 2018-07-20 23:20
@Lmawhinney7175 Can you update ArcGIS Pro to the latest released version (2.2) and then give it a try?

**Comment by Lmawhinney7175** [comment] 2018-07-20 23:22
You know that is a good idea.  I will check, but I don't think I will be able to?

**Comment by Kevin-GIS** [comment] 2019-11-16 01:00
Closing this issue for the time being, can reopen if this issue is still reproducible.

**Closed by Kevin-GIS** 2019-11-16 01:00 UTC
