### ISSUE TITLE
Recreate Geometry Z Value not hold

### ISSUE THREAD

**Issue by ArgusW** [Esri/collector-tools#68] opened 2018-09-28 14:25 UTC
Great script, but when I have a feature class that has a value for a feature height that in the schema is called height, the script wants to use this that field.  In ArcPro 2.2, when I select the GNSS recorded "Altitude" field, the window will default back to the first instance of anything that appears to be height or elevation.  My thought is the script is grabbing the first instance it see is a Z value, not the one I want it grab.  

Maybe there is another step I was not aware when using this script.

Thank you.

**Comment by Kevin-GIS** [comment] 2018-09-28 16:41
Hi @ArgusW thanks for the feedback. I have a few questions for you:

You've captured GPS data in the field and would like to obtain orthometric/msl height from the GNSS metadata fields, namely the Altitude field through the use of the Project Z tool. Is that correct?

Are you running Project Z or Recreate Geometry? (Project Z is a model that, among other tools, it includes the Recreate Geometry tool as part of it.)

From your explanation, it sounds like you have multiple 'height' related fields in your attribute scheme, where you're unable to select the correct one. Is that correct? Could you share a screenshot of your schema?

Thanks for the information.

**Comment by locontem** [comment] 2018-11-28 19:55
Hi Kevin,

I am responding because I have had this problem for a while now, when using the Project Z model I select the Altitude column for the Z-values (this feature class has the GNSS metadata columns), but then after tabbing out of the area it defaults back to the first Double column in my feature class. I am attaching a screenshot of my schema, you will see that the Rim Elevation is the first Double column in my dataset and the Altitude column is farther down the list. Also attached is an animated gif showing how the model behaves when selecting the Altitude column.

Mike

![arcgis collector projectz error](https://user-images.githubusercontent.com/23244056/49178185-f1ae8d00-f303-11e8-8830-c16ac0577e1b.gif)
![arcgis collector projectz schema](https://user-images.githubusercontent.com/23244056/49178186-f1ae8d00-f303-11e8-9a5b-237c202be3c8.png)

**Comment by apulverizer** [comment] 2018-11-29 14:22
@locontem @ArgusW 

I was able to reproduce it. I believe this is fixed in my branch. Feel free to give a shot.

Checkout/download this branch and try it:
https://github.com/Esri/collector-tools/tree/aaron/validation-fix

**Comment by locontem** [comment] 2018-11-29 17:38
@apulverizer 

Yes! Thank you for the fix! It let me set up the Altitude field now and I have it chugging away and a mass of points!

Mike

**Closed** 2018-12-04 17:06 UTC
