### ISSUE TITLE
Unable to select transformations

### ISSUE THREAD

**Issue by shepardb** [Esri/collector-tools#21] opened 2017-09-27 17:38 UTC
I've tried the ProjectZ tool in both ArcMap and ArcPro.  Neither allow me to select a transformation.  Also, in testing a dataset, the Z values provided only seem to convert units (i.e. meters to feet).  Is an ellipsoid to geoid transformation supported (e.g. ITRF 2008 to NAVD88)?  The Z values output are only the GNSS "Altitude" field multiplied by 3.28.  They're not close to the reported NAVD88 height of a nearby benchmark.

**Comment by Kevin-GIS** [comment] 2017-10-09 17:15
Hi Shepard,

Have you installed the ArcGIS Coordinate Systems Data, which includes the vertical datum transformations? This could be why you cannot select a transformation. 

This would have been a separate installation starting at ArcGIS Desktop 10.4.x. 

http://desktop.arcgis.com/en/arcmap/latest/get-started/installation-guide/introduction.htm - See ArcGIS Desktop components

Here is a good post on the coordinate systems data install - https://community.esri.com/thread/187865-information-on-the-coordinate-systems-desktop-install

Thank you. 
Kevin

**Comment by shepardb** [comment] 2017-10-11 15:10
I just installed ArcGIS Coordinate Systems Data for ArcGIS for Desktop.   I'm on v 10.4.1.  As mentioned in the links provided, the documentation is sparse.  It appears to have installed correctly, and I rebooted, but I still don't have any options when I try to add a transformation (+ button on the Geographic Transformation parameter).  I'd like to do both horizontal and vertical transformations, but I can change our data collection so that I only need to do vertical.  I've tried specifying a few different input coordinate systems to see if that was an issue, but nothing I've tried will allow me to select a transformation.  The x, y, and z parameters all auto-populate correctly.  I'm using an export from Collector/AGOL, so I'm relying on Project Z/Recreate Geometry to create the Z enabled point layer.  I get a warning on the Geographic Transformation parameter: 001839, a datum transformation is expected, but the parameter is empty.  Nothing happens when I click the + button.

**Comment by Kevin-GIS** [comment] 2017-10-11 17:23
@shepardb 

Thank you for that information. I have a few questions to understand your data and environment:

1. For your map in Collector, what is the GCS/PCS you're using for your operational layers? i.e. the feature services?

2. Are you using an AGOL basemap or your own that you've cached via a TPK or map service?

3. From question 2, if you are using your own basemap, what is the GCS/PCS being used?

4. When capturing data in Collector via the GPS, what type of GPS receiver are you working with?

5. What type of real-time correction service(s) are you working with? i.e. RTK via an NTRIP connection, PPP subscription service, etc. 

6. What is the datum of the correction service you're using?

Also, here is a Word document that further explains, w/screenshots, how to configure the ProjectZ tool in general. 

Please review the document and please let me know which step(s) you're stuck on. 

And to answer your first question, yes, this tool is designed to ultimately take the values from within the Altitude GNSS metadata field and inject them into the Z geometry of the output feature class, while also performing a vertical datum transformation to convert those heights from HAE to MSL. 

**Note** - We are currently working on enhancing this tool to address a known issue with not retaining relationships/attachments from the input feature class on the output feature class. Therefore please be aware of this issue. 

Thanks
-Kevin

[Collector ProjectZ Tool.docx](https://github.com/Esri/collector-tools/files/1376563/Collector.ProjectZ.Tool.docx)

**Comment by shepardb** [comment] 2017-10-11 23:05
I think this is going to help out with more than just using this tool, as I'm not completely confident that I'm doing this correctly.

1. WGS 1984 Web Mercator Auxiliary Sphere
2. AGOL basemap (should also be above PCS)
3. n/a
4. Arrow 200, with a Collector profile set up to transform NAD83 2011 to WGS 1984 Web Mercator Auxiliary Sphere
5. RTK via NTRIP
6. NAD83 2011

I recently collected points on vertically controlled NGS benchmarks and "Altitude" field values match those on the NGS datasheet which were recorded in VCS NAD83 2011 ellipsoid height (within a couple cm).

I've attached a screenshot of the dialog.  The Input warning is just specifying that Z values aren't present and they'll be created.  The Geographic Transformation warning is that a transformation isn't specified.  When I click the + button to specify one, nothing happens.  Shouldn't I be able to use the geoid12b data from the installed ArcGIS Coordinate Systems Data to transform NAD83 2011 ellipsoid to NAVD88?

![project z error](https://user-images.githubusercontent.com/32338054/31471458-b3a9ec80-ae9d-11e7-90ea-619e2b43c5b2.PNG)

**Comment by shepardb** [comment] 2017-10-30 20:03
Bumping as it's been a while and I'm still having this issue.

**Comment by miaogeng** [comment] 2017-11-01 21:54
@shepardb sorry for late response. The reason why it doesn't show up because there is no vertical datum transformation found with NAD_1983_HARN as horizontal. Geoid12b works for NAD83_2011. I think this is expected. 

While investigating this, I notice US ft at NAVD88_height_(ftUS) is another factor. It is better to use NAVD_1988 WKID: 5703 Linear Units: Meter. 

Here is my workaround suggestion: you use projectZ tool to project into into NAD_1983_2011 based spatial reference first, and then do horizontal only datum transformation to convert into NAD_1983_HARN_StatePlane_Oregon_North_FIPS_3601_Feet_Intl.  

Also in your screen shot, you use WGS84 Web Mercator as input coordinate system and NAD 1983 2011 as vertical. The lat/long/altitude in metadata field are raw data from GNSS receivers. You use RTK with correction source in NAD 1983 2011. Both horizontal and vertical in input coordinate system should be NAD 1983 2011. 

You should use NGS control point to check if it meets your project requirements. 

Step 1: Use ProjectZ tool to project into into the following spatial reference
Horizontal: NAD_1983_2011_StatePlane_Oregon_North_FIPS_3601_Ft_Intl (WKID: 6559)
Vertical: NAVD_1988 (WKID: 5703)
![image](https://user-images.githubusercontent.com/19719166/32299330-73635d16-bf12-11e7-91f1-9c66c30aaff0.png)

Step 2: Use System tools > Project tool to do horizontal datum transformation 

![image](https://user-images.githubusercontent.com/19719166/32299834-427ae4ce-bf14-11e7-8d5e-c08cd14ef700.png)

**Comment by shepardb** [comment] 2017-11-02 21:19
For whatever reason, I still wasn't able to get a transformation when using WKIDs: 6559 and 5703 for the output CS.  It did, however, work when I used GCS NAD_1983_2011 for both the input and output horizontal CS, and set the output VCS to WKID 5703.  It does make sense to do the horizontal transformation after the vertical.  I assumed the tool may do both in that order, but looking at Project Z in Model Builder, it only appears to do the vertical projection.  That's fine as I'm modifying it to then add the X, Y, Z values, calculate the NAVD88 elevations from meters to feet and then do the horizontal projection.  Good news is the Geoid12b values (Z-Altitude), and the NAVD88 feet match the NGS datasheet for the benchmarks (within a couple inches).

Not totally related to this, but I'm now thinking I should publish a new point feature services to AGOL in GCS NAD_1983_2011 rather than WGS 1984 Web Mercator Auxiliary Sphere.  It seems to work fine, but I'm not sure that it's necessary to have the feature service in the same CS as the map.  Since this tool was created for Collector, any insight on best practices for setting up/collecting the input data?

Thanks,
Brian

**Comment by miaogeng** [comment] 2017-11-02 22:01
if a transformation doesn't show, it can mean it can't find it due to various reasons, like it doesn't exist, or it involves more than two steps. 

ProjectZ tool is an extension of Project tool. It can do both horizontal and vertical. 

It is good to hear that it matches the NGS datasheet.

If you are using Esri basemap as your webmap basemap, publishing feature service to AGOL in WGS 1984 Web Mercator or NAD1983_2011, either are fine as long as you define datum transformation method in data frame. You will be interested to learn more at https://blogs.esri.com/esri/arcgis/2015/08/10/using-gnss-receivers-with-collector-for-arcgis/

**Comment by Kevin-GIS** [comment] 2019-11-16 01:03
Closing this issue for the time being, can reopen if this issue is still reproducible.

**Closed by Kevin-GIS** 2019-11-16 01:03 UTC
